# Generated by Django 4.2.2 on 2023-06-27 19:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Not Gievn', max_length=50)),
                ('lastname', models.CharField(default='Not Given', max_length=50)),
                ('year_born', models.DateField(default='Not given')),
                ('nationality', models.CharField(default='Not Given', max_length=50)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='BookCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book_category',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('year_written', models.PositiveIntegerField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.authormodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookcategorymodel')),
            ],
        ),
    ]
